resource "aws_api_gateway_rest_api" "this" {
  name        = "onetime"
  description = "One-time secret sharing"

  endpoint_configuration {
    types = ["REGIONAL"]
  }

  body = templatefile("${path.module}/openapi.yaml", {
    create_invoke_arn   = aws_lambda_function.this["create"].invoke_arn
    retrieve_invoke_arn = aws_lambda_function.this["retrieve"].invoke_arn
    allowed_origin      = var.allowed_origin
  })
}

resource "aws_api_gateway_deployment" "this" {
  rest_api_id = aws_api_gateway_rest_api.this.id

  # Without a trigger this resource never changes, so apply reports success
  # and production keeps serving the previous definition.
  triggers = {
    redeployment = sha1(aws_api_gateway_rest_api.this.body)
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_api_gateway_stage" "prod" {
  rest_api_id   = aws_api_gateway_rest_api.this.id
  deployment_id = aws_api_gateway_deployment.this.id
  stage_name    = "prod"
}

resource "aws_api_gateway_method_settings" "prod" {
  rest_api_id = aws_api_gateway_rest_api.this.id
  stage_name  = aws_api_gateway_stage.prod.stage_name
  method_path = "*/*"

  settings {
    throttling_rate_limit  = 20
    throttling_burst_limit = 40
  }
}

# Gateway responses are generated by API Gateway itself, before and around the
# integration, so they do not inherit the headers the Lambdas set. A 404 is an
# ordinary outcome here rather than a failure; without these the browser
# reports a CORS error and the reveal page never learns the real status.
#
# The nested single quotes are required — the value is a VTL string literal.
# Omitting them fails silently, at runtime, with no error at apply time.
resource "aws_api_gateway_gateway_response" "default_4xx" {
  rest_api_id   = aws_api_gateway_rest_api.this.id
  response_type = "DEFAULT_4XX"

  response_parameters = {
    "gatewayresponse.header.Access-Control-Allow-Origin" = "'${var.allowed_origin}'"
  }
}

resource "aws_api_gateway_gateway_response" "default_5xx" {
  rest_api_id   = aws_api_gateway_rest_api.this.id
  response_type = "DEFAULT_5XX"

  response_parameters = {
    "gatewayresponse.header.Access-Control-Allow-Origin" = "'${var.allowed_origin}'"
  }
}

# A separate resource, and easy to forget. Without it API Gateway cannot
# invoke the function and returns a 500 with nothing useful in it.
resource "aws_lambda_permission" "apigw" {
  for_each = local.functions

  statement_id  = "AllowAPIGatewayInvoke"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.this[each.key].function_name
  principal     = "apigateway.amazonaws.com"
  source_arn    = "${aws_api_gateway_rest_api.this.execution_arn}/*/*"
}

output "api_invoke_url" {
  description = "Stage URL. Use this until the custom domain is in place."
  value       = aws_api_gateway_stage.prod.invoke_url
}
